apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taller-storage-pvc
spec:
  accessModes:
    - ReadWriteMany # Esto permite que el Front y el Back se conecten a la vez
  resources:
    requests:
      storage: 5Gi