apiVersion: v1
kind: Service
metadata:
  name: backend-service # Nombre único del servicio en Kubernetes
spec:
  selector:
    app: backend-taller # Redirige el tráfico hacia los Pods que tengan esta etiqueta
  ports:
    - protocol: TCP # Protocolo de comunicación de red
      port: 8080 # Puerto expuesto dentro del clúster 
      targetPort: 8080 # Puerto interno real del contenedor backend donde llega el tráfico