apiVersion: v1
kind: Service
metadata:
  name: frontend-service # Nombre único del servicio para el frontend
spec:
  selector:
    app: frontend-taller # Redirige el tráfico web a los Pods del frontend
  ports:
    - protocol: TCP # Protocolo de red estándar para tráfico HTTP
      port: 80 # Puerto por el que el servicio escucha dentro del clúster
      targetPort: 80 # Puerto real del contenedor Nginx donde llega la petición